---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog.fanite.com
  namespace: website
  labels:
    app.kubernetes.io/name: hexo-blog-certificate
    app.kubernetes.io/component: hexo-blog
    app.kubernetes.io/created-by: fanite
spec:
  secretName: blog.fanite.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - blog.fanite.com