apiVersion: v1
kind: Service
metadata:
  name: hexo-blog
  labels:
    app.kubernetes.io/name: hexo-blog
    app.kubernetes.io/component: hexo-blog
spec:
  selector:
    app: hexo-blog
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
